version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /root/Bouffe:/home/node/app
    expose:
      - "3000"
    ports:
    - "3000:3000"
    command: "node server.js"

